export const demoMachines = [
  {
    id: "1005",
    name: "חנקן 1005",
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2022/1/OS/HW/QW/71651973/psa-nitrogen-generator.jpg",
    currentTemp: -40,
    currentNitrogen: 13,
    nextTemp: -38,
    nextNitrogen: 15,
    products: [
      {
        id: 1,
        name: "אי-רגיל 0.5",
        units: 3000,
        processTime: "1:13",
        progress: 45,
        inQueue: false,
        isRing: true,
        color: "green",
      },
      {
        id: 2,
        name: "אי-רגיל 0.4",
        units: 9000,
        processTime: "5:00",
        inQueue: true,
        isRing: true,
        color: "black",
      },
      {
        id: 3,
        name: "אצבעות מריטה 4.5",
        units: 1000,
        processTime: "3:30",
        inQueue: true,
        isRing: false,
        color: "red",
      },
      {
        id: 3,
        name: "אצבעות מריטה 4.5",
        units: 1000,
        processTime: "3:30",
        inQueue: true,
        isRing: false,
        color: "red",
      },
      {
        id: 3,
        name: "אצבעות מריטה 4.5",
        units: 1000,
        processTime: "3:30",
        inQueue: true,
        isRing: false,
        color: "red",
      },
      {
        id: 3,
        name: "אצבעות מריטה 4.5",
        units: 1000,
        processTime: "3:30",
        inQueue: true,
        isRing: false,
        color: "red",
      },
      {
        id: 3,
        name: "אצבעות מריטה 4.5",
        units: 1000,
        processTime: "3:30",
        inQueue: true,
        isRing: false,
        color: "red",
      },
      {
        id: 3,
        name: "אצבעות מריטה 4.5",
        units: 1000,
        processTime: "3:30",
        inQueue: true,
        isRing: false,
        color: "red",
      },

    ],
  },
  {
    id: "1006",
    name: "חנקן 1006",
    imageUrl:
      "https://5.imimg.com/data5/SELLER/Default/2022/12/GJ/QF/BT/144028/psa-nitrogen-plants-500x500.jpg",
    currentTemp: -42,
    currentNitrogen: 11,
    nextTemp: -39,
    nextNitrogen: 14,
    products: [
      {
        id: 1,
        name: "אי-רגיל 0.3",
        units: 5000,
        processTime: "2:30",
        progress: 45,
        inQueue: false,
        isRing: true,
        color: "green",
      },
      {
        id: 2,
        name: "אי-רגיל 0.7",
        units: 7500,
        processTime: "4:15",
        progress: 0,
        inQueue: true,
        isRing: true,
        color: "blue",
      },
    ],
  },
];

export const demoProducts = [
  {
    id: 1,
    name: "אי-רגיל 0.4",
    units: 9000,
    processTime: "5:00",
    status: "new",
    date: "14/11/24",
    time: "13:40",
    color: "black",
    colorName: "שחור",
    order: "IM302",
    isRing: true,
    progress: 0,
  },
  {
    id: 2,
    name: "אי-רגיל 0.4",
    units: 9000,
    processTime: "5:00",
    status: "new",
    date: "14/11/24",
    time: "13:29",
    color: "black",
    colorName: "שחור",
    order: "IM302",
    isRing: true,
    progress: 0,
  },
  {
    id: 3,
    name: "אי-רגיל 0.4",
    units: 9000,
    processTime: "5:00",
    machine: "חנקן 1005",
    machineId: "1005",
    status: "inProcess",
    date: "14/11/24",
    time: "03:15",
    color: "black",
    colorName: "שחור",
    progress: 65,
    order: "IM302",
    isRing: true,
    processSteps: [
      {
        id: "1003",
        name: "חנקן",
        startDate: "03/03/25",
        startTime: "13:31",
        endDate: "04/03/25",
        endTime: "12:31",
      },
      {
        id: "1006",
        name: "שיוף",
        startDate: "03/03/25",
        startTime: "13:31",
        endDate: "04/03/25",
        endTime: "12:31",
      },
      {
        id: "1013",
        name: "שטיפה",
        startDate: "---",
        startTime: "---",
        endDate: "",
        endTime: "",
      },
    ],
  },
  {
    id: 4,
    name: "אצבעות מריטה 5.0",
    units: 9000,
    processTime: "5:00",
    status: "inProcess",
    machine: "חנקן 1005",
    machineId: "1005",
    date: "14/11/24",
    time: "13:29",
    color: "red",
    colorName: "אדום",
    order: "IM302",
    isRing: false,
    progress: 25,
  },
  {
    id: 5,
    name: "אי-רגיל 0.7",
    units: 9000,
    processTime: "5:00",
    status: "inProcess",
    date: "14/11/24",
    time: "13:29",
    color: "yellow",
    colorName: "צהוב",
    order: "IM302",
    isRing: true,
    progress: 0,
  },
  {
    id: 6,
    name: "אי-רגיל 0.5",
    units: 9000,
    processTime: "5:00",
    status: "inProcess",
    date: "14/11/24",
    time: "13:29",
    color: "blue",
    colorName: "כחול",
    order: "IM302",
    isRing: true,
    progress: 0,
  },
  {
    id: 7,
    name: "אי-רגיל 0.4",
    units: 9000,
    processTime: "5:00",
    status: "completed",
    date: "14/11/24",
    time: "13:29",
    color: "black",
    colorName: "שחור",
    order: "IM302",
    isRing: true,
    progress: 100,
  },
  {
    id: 8,
    name: "אצבעות מריטה 5.0",
    units: 7500,
    processTime: "5:00",
    status: "completed",
    date: "14/11/24",
    time: "13:29",
    color: "purple",
    colorName: "סגול",
    order: "IM302",
    isRing: false,
    progress: 100,
  },
  {
    id: 9,
    name: "אי-רגיל 0.4",
    units: 4000,
    processTime: "5:00",
    status: "completed",
    date: "14/11/24",
    time: "13:29",
    color: "red",
    colorName: "אדום",
    order: "IM302",
    isRing: true,
    progress: 100,
  },
];

export const demoFloor = [
  {
    id: "1005",
    name: "חנקן 1005",
    type: "חנקן",
    status: "running",
    currentProduct: "אי-רגיל 0.5",
    nextProduct: "אי-רגיל 0.4",
    timeRemaining: "00:08",
    isDelayed: false,
  },
  {
    id: "1008",
    name: "שטיפה 1008",
    type: "שטיפה",
    status: "delayed",
    currentProduct: "אי-רגיל 0.5",
    nextProduct: "אי-רגיל 0.4",
    timeRemaining: "00:04",
    isDelayed: true,
  },
  {
    id: "1009",
    name: "שטיפה 1009",
    type: "שטיפה",
    status: "running",
    currentProduct: "אי-רגיל 0.5",
    nextProduct: "אי-רגיל 0.4",
    timeRemaining: "00:15",
    isDelayed: false,
  },
  {
    id: "1004",
    name: "חנקן 1004",
    type: "חנקן",
    status: "waiting",
    currentProduct: "ממתין בתור: אי-רגיל 0.5",
    nextProduct: "אי-רגיל 0.4",
    timeRemaining: "",
    isDelayed: false,
  },
  {
    id: "1001",
    name: "שיוף 1001",
    type: "שיוף",
    status: "running",
    currentProduct: "אי-רגיל 0.5",
    nextProduct: "אי-רגיל 0.4",
    timeRemaining: "00:08",
    isDelayed: false,
  },
  {
    id: "1003",
    name: "חנקן 1003",
    type: "חנקן",
    status: "error",
    currentProduct: "---",
    nextProduct: "---",
    timeRemaining: "--:--",
    isDelayed: false,
  },
  {
    id: "1002",
    name: "שיוף 1002",
    type: "שיוף",
    status: "running",
    currentProduct: "אי-רגיל 0.5",
    nextProduct: "אי-רגיל 0.4",
    timeRemaining: "00:08",
    isDelayed: false,
  },
];
